
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "NUVPD"."VIEW_EMPRESAS" ("NUMERO", "DESCRIPCION", "AB_CLAVE", "AB_DESC", "RFC", "DIRECCION") AS 
  select
COMPANIA.CCCO as NUMERO
,TRIM(COMPANIA.CCNAME) as DESCRIPCION
,COMPANIA.CCAN8 as AB_CLAVE
,TRIM(ABOOK.ABALPH || ADDRESS.ALADD1) as AB_DESC
,trim(ABOOK.ABTAX) as RFC
,TRIM(ADDRESS.ALADD2) || ' ' || TRIM(ADDRESS.ALADD3) || ' ' || TRIM(ADDRESS.ALADD4) || ' ' || TRIM(ADDRESS.ALADDZ) || ' ' || TRIM(ADDRESS.ALCTY1) as DIRECCION

from PRODDTA.F0010 COMPANIA

left outer join PRODDTA.F0101 ABOOK on 1=1 
            and ABOOK.ABAN8 = COMPANIA.CCAN8
            
left outer join PRODDTA.F0116 ADDRESS on 1=1
            and ADDRESS.ALAN8 = COMPANIA.CCAN8
            and ADDRESS.ALEFTB = 0

where 1=1
and compania.CCAN8 not in (0,5);
