
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "NUVPD"."VIEW_EBUDGETS" ("COMPANIA", "ANIO", "PROYECTO", "PROYECTO_DESC", "UN", "UN_DESC", "CUENTA_CLASIF", "CUENTA_DESC", "CUENTA_OBJETO", "CUENTA_AUXILIAR", "CUENTA_ID", "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE") AS 
  SELECT
SALDOS.GBCO AS COMPANIA
,SALDOS.GBFY AS ANIO

,trim(UNS.MCRP01) AS PROYECTO
,TRIM(PROYS.DRDL01 || PROYS.DRDL02) AS PROYECTO_DESC

,SALDOS.GBMCU AS UN
,UNS.MCDL01 AS UN_DESC

,TRIM(CLASIF.DRDL01) AS CUENTA_CLASIF 
,TRIM(CUENTA.GMDL01) AS CUENTA_DESC
,TRIM(CUENTA.GMOBJ) AS CUENTA_OBJETO
,TRIM(CUENTA.GMSUB) AS CUENTA_AUXILIAR

,SALDOS.GBAID AS CUENTA_ID

,SALDOS.GBAN01/100 AS ENERO 
,SALDOS.GBAN02/100 AS FEBRERO
,SALDOS.GBAN03/100 AS MARZO
,SALDOS.GBAN04/100 AS ABRIL
,SALDOS.GBAN05/100 AS MAYO
,SALDOS.GBAN06/100 AS JUNIO
,SALDOS.GBAN07/100 AS JULIO
,SALDOS.GBAN08/100 AS AGOSTO
,SALDOS.GBAN09/100 AS SEPTIEMBRE
,SALDOS.GBAN10/100 AS OCTUBRE
,SALDOS.GBAN11/100 AS NOVIEMBRE
,SALDOS.GBAN12/100 AS DICIEMBRE

FROM PRODDTA.F0902 SALDOS 

LEFT OUTER JOIN PRODDTA.F0006 UNS
             ON UNS.MCMCU = SALDOS.GBMCU

LEFT OUTER JOIN PRODCTL.F0005 PROYS
             ON PROYS.DRSY = '00'    
            AND PROYS.DRRT = '01'    
            AND TRIM(PROYS.DRKY) = TRIM(UNS.MCRP01)             

LEFT OUTER JOIN PRODDTA.F0901 CUENTA
             ON CUENTA.GMAID = SALDOS.GBAID  

LEFT OUTER JOIN PRODCTL.F0005 CLASIF
             ON CLASIF.DRSY = '09'    
            AND CLASIF.DRRT = '10'    
            AND TRIM(CLASIF.DRKY) = TRIM(CUENTA.GMR010)   

WHERE 1=1
AND SALDOS.GBLT = 'BA';
