  CREATE OR REPLACE FORCE EDITIONABLE VIEW "NUVPD"."VIEW_GASTOS_AUTORIZADORES" ("EMPLEADO_CLAVE", "EMPLEADO_NOMBRE", "EMPLEADO_NCORTO", "GRUPO_CLAVE", "GRUPO_DESCRIPCION", "AUTORIZADOR_CLAVE", "AUTORIZADOR_NOMBRE") AS 
  select
ABOOK.ABAN8 as EMPLEADO_CLAVE
,trim(NVL(ABOOK.ABALPH, '-')) as EMPLEADO_NOMBRE
,trim(NVL(ABOOK.ABDC, '-')) as EMPLEADO_NCORTO
,trim(NVL(EGROUP.GPGRPPROF, '-')) as GRUPO_CLAVE
,trim(NVL(EGROUP.GPDL01, '-')) as GRUPO_DESCRIPCION
,trim(NVL(EMPLEADOS.EPMGRID, 0)) as AUTORIZADOR_CLAVE
,trim(NVL(ABOOK_APROV.ABALPH, '-')) as AUTORIZADOR_nombre
from PRODDTA.F0101 ABOOK

----------- Employe Profile -----------
left outer join PRODDTA.F20103 EMPLEADOS on 1=1 
            and EMPLEADOS.EPEMPLOYID = ABOOK.ABAN8

----------- Expense Groups -----------
left outer join PRODDTA.F20104 EGROUP on 1=1
            and egroup.GPGRPPROF = empleados.EPGRPPROF 

----------- Adress Book for Approves -----------
left outer join PRODDTA.F0101 ABOOK_APROV on 1=1
            AND ABOOK_APROV.ABAN8 = EMPLEADOS.EPMGRID

where 1=1;
