
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "NUVPD"."VIEW_BUDGETS" ("ANIO", "LIBRO", "COMPANIA", "UN", "UN_DESC", "UN_PROYECTO", "UN_PROYECTO_DESC", "UN_PROYECTO_ZONA", "UN_PROYECTO_TIPO", "UN_PROYECTO_ESTADO", "CUENTA", "CUENTA_DESC", "CUENTA_OBJETO", "CUENTA_AUXILIAR", "CUENTA_NIVEL", "CUENTA_ESTADO", "CUENTA_ESTADO_DESC", "CUENTA_MONEDA", "CUENTA_TIPO", "CUENTA_TIPO_DESC", "CUENTA_CLASE", "CUENTA_CLASE_DESC", "CUENTA_FLUJO", "CUENTA_FLUJO_DESC", "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE", "TOTAL") AS 
  select
        BUDGET.GBFY as ANIO
        ,BUDGET.GBLT AS LIBRO

        ,BUDGET.GBCO AS COMPANIA
        ,TRIM(BUDGET.GBMCU) as UN
        ,CENTRO.MCDL01 as UN_DESC
        
        ,TRIM(CENTRO.MCRP01) as UN_PROYECTO
        ,NVL(TRIM(PROYECTO.DRDL01),'-') as UN_PROYECTO_DESC 
        ,nvl(TRIM(PROYECTO.DRDL02),'-') as UN_PROYECTO_ZONA
        ,NVL(TRIM(PROYECTO.DRSPHD),' ') as UN_PROYECTO_TIPO
        ,NVL(TRIM(PROYECTO.DRHRDC),'-') as UN_PROYECTO_ESTADO 

        ,BUDGET.GBAID as CUENTA
        ,TRIM(CUENTA.GMDL01) as CUENTA_DESC
        ,TRIM(CUENTA.GMOBJ) as CUENTA_OBJETO
        ,TRIM(CUENTA.GMSUB) as CUENTA_AUXILIAR        
        ,CUENTA.GMLDA as CUENTA_NIVEL
        ,CUENTA.GMPEC as CUENTA_ESTADO
        ,NVL(TRIM(ESTADO.DRDL01),'Activa') as CUENTA_ESTADO_DESC
        ,CUENTA.GMCRCD as CUENTA_MONEDA           
        ,NVL(TRIM(CUENTA.GMR011),'-') as CUENTA_TIPO
        ,NVL(TRIM(TIPO.DRDL01),'SIN TIPO') as CUENTA_TIPO_DESC
        ,NVL(TRIM(CUENTA.GMR010),'-') as CUENTA_CLASE
        ,NVL(TRIM(CLASE.DRDL01),'SIN CLASIFICACION') as CUENTA_CLASE_DESC
        ,NVL(TRIM(CUENTA.GMR009),'-') as CUENTA_FLUJO
        ,NVL(TRIM(FLUJO.DRDL01),'SIN FLUJO') as CUENTA_FLUJO_DESC        
        
        ,BUDGET.GBAN01/100 as ENERO 
        ,BUDGET.GBAN02/100 as FEBRERO 
        ,BUDGET.GBAN03/100 as MARZO 
        ,BUDGET.GBAN04/100 as ABRIL 
        ,BUDGET.GBAN05/100 as MAYO 
        ,BUDGET.GBAN06/100 AS JUNIO 
        ,BUDGET.GBAN07/100 as JULIO  
        ,BUDGET.GBAN08/100 as AGOSTO 
        ,BUDGET.GBAN09/100 as SEPTIEMBRE 
        ,BUDGET.GBAN10/100 as OCTUBRE 
        ,BUDGET.GBAN11/100 as NOVIEMBRE 
        ,BUDGET.GBAN12/100 AS DICIEMBRE 
        ,(BUDGET.GBAN01/100 + BUDGET.GBAN02/100 + BUDGET.GBAN03/100 + BUDGET.GBAN04/100 + BUDGET.GBAN05/100 + BUDGET.GBAN06/100 + BUDGET.GBAN07/100 + BUDGET.GBAN08/100 + BUDGET.GBAN09/100 + BUDGET.GBAN10/100 + BUDGET.GBAN11/100 + BUDGET.GBAN12/100) AS TOTAL
        from PRODDTA.F0902 BUDGET      
        
        LEFT OUTER JOIN PRODDTA.F0901 CUENTA
                     ON CUENTA.GMAID = BUDGET.gbaid   
        
        LEFT OUTER JOIN proddta.F0006 CENTRO
                     ON CENTRO.MCMCU = BUDGET.GBMCU
                     
        LEFT OUTER JOIN PRODCTL.F0005D ESTADO
                     ON ESTADO.DRSY = 'H00'    
                    AND ESTADO.DRRT = 'PE'    
                    AND TRIM(ESTADO.DRKY) = trim(CUENTA.GMPEC)                     
        
        LEFT OUTER JOIN PRODCTL.F0005 PROYECTO
                     ON PROYECTO.DRSY = '00'    
                    AND PROYECTO.DRRT = '01'
                    AND TRIM(PROYECTO.DRKY) = trim(CENTRO.MCRP01)   

        LEFT OUTER JOIN PRODCTL.F0005 TIPO
                 ON TIPO.DRSY = '09'    
                AND TIPO.DRRT = '11'    
                AND TRIM(TIPO.DRKY) = trim(CUENTA.gmr011)                    
        
        LEFT OUTER JOIN PRODCTL.F0005 CLASE
                     ON CLASE.DRSY = '09'    
                    AND CLASE.DRRT = '10'    
                    AND TRIM(CLASE.DRKY) = trim(CUENTA.gmr010)
                    
        LEFT OUTER JOIN PRODCTL.F0005 FLUJO
                     ON FLUJO.DRSY = '09'    
                    and FLUJO.DRRT = '09'    
                    AND TRIM(FLUJO.DRKY) = trim(CUENTA.gmr009)
                    
        where 1=1
        and BUDGET.GBAN01 <> 0
        and BUDGET.GBAN02 <> 0
        and BUDGET.GBAN03 <> 0
        and BUDGET.GBAN04 <> 0
        and BUDGET.GBAN05 <> 0
        and BUDGET.GBAN06 <> 0
        and BUDGET.GBAN07 <> 0
        and BUDGET.GBAN08 <> 0
        and BUDGET.GBAN09 <> 0
        and BUDGET.GBAN10 <> 0
        and BUDGET.GBAN11 <> 0
        and BUDGET.GBAN12 <> 0

        and BUDGET.GBLT = 'BA';
