
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "NUVPD"."VIEW_ICASM" ("ICA", "COMPANIA", "DOC_TIPO", "GL_CODIGO", "ORDEN_TIPO", "COSTO_TIPO", "UN", "OBJETO", "AUXILIAR", "CUENTA_NUMERO", "CUENTA_ID", "CUENTA_DESCRIPCION", "CUENTA_UN", "CUENTA_UN_DESC", "CUENTA_UN_TIPO", "CUENTA_OBJETO", "CUENTA_AUXILIAR", "CUENTA_ESTADO", "CUENTA_ESTADO_DESC") AS 
  SELECT ICA.MLANUM AS ICA,
          ICA.MLCO AS COMPANIA,
          ICA.MLDCT AS DOC_TIPO,
          ICA.MLGLPT AS GL_CODIGO,
          ICA.MLDCTO AS ORDEN_TIPO,
          ICA.MLCOST AS COSTO_TIPO,
          NVL (TRIM (ICA.MLMCU), '-') AS UN,
          TRIM (ICA.MLOBJ) AS OBJETO,
          NVL (TRIM (ICA.MLSUB), '-') AS AUXILIAR,
          (   TRIM (ICA.MLMCU)
           || '.'
           || TRIM (ICA.MLOBJ)
           || '.'
           || TRIM (ICA.MLSUB))
             AS CUENTA_NUMERO,
          CUENTA.GMAID AS CUENTA_ID,
          TRIM (CUENTA.GMDL01) AS CUENTA_DESCRIPCION,
          TRIM (CUENTA.GMMCU) AS CUENTA_UN,
          TRIM (CENTRO.MCDL01) AS CUENTA_UN_DESC,
          NVL (TRIM (CENTRO.MCSTYL), '-') AS CUENTA_UN_TIPO,
          TRIM (CUENTA.GMOBJ) AS CUENTA_OBJETO,
          NVL (TRIM (CUENTA.GMSUB), '-') AS CUENTA_AUXILIAR,
          CUENTA.GMPEC AS CUENTA_ESTADO,
          NVL (TRIM (ESTADO.DRDL01), 'Activa') AS CUENTA_ESTADO_DESC
     FROM PRODDTA.F4095 ICA
          LEFT OUTER JOIN PRODDTA.F0901 CUENTA
             ON     1 = 1
                AND CUENTA.GMCO = ICA.MLCO
                AND CUENTA.GMOBJ = ICA.MLOBJ
                AND CUENTA.GMSUB = ICA.MLSUB
          LEFT OUTER JOIN PRODDTA.F0006 CENTRO
             ON CENTRO.MCMCU = CUENTA.GMMCU
          LEFT OUTER JOIN PRODCTL.F0005D ESTADO
             ON     1 = 1
                AND ESTADO.DRSY = 'H00'
                AND ESTADO.DRRT = 'PE'
                AND TRIM (ESTADO.DRKY) = TRIM (CUENTA.GMPEC);
