
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "NUVPD"."VIEW_IFACTURAS" ("DOC_COMPANIA", "DOC_TIPO", "DOC", "CLIENTE", "BENEFICIARIO", "UN", "FECHA_LM", "MONTO_TOTAL_MX", "MONTO_PENDIENTE_MX", "MONTO_IMPONIBLE_MX", "MONTO_NOIMPONIBLE_MX", "MONTO_IMPUESTO_MX") AS 
  SELECT
DOC_COMPANIA
,DOC_TIPO
,DOC
,CLIENTE
,BENEFICIARIO
,UN
,FECHA_LM
,SUM(MONTO_TOTAL_MX) AS MONTO_TOTAL_MX
,SUM(MONTO_PENDIENTE_MX) AS MONTO_PENDIENTE_MX
,SUM(MONTO_IMPONIBLE_MX) AS MONTO_IMPONIBLE_MX
,SUM(MONTO_NOIMPONIBLE_MX) AS MONTO_NOIMPONIBLE_MX
,SUM(MONTO_IMPUESTO_MX) AS MONTO_IMPUESTO_MX
FROM (
        SELECT
        FACTURA.RPDOC AS DOC
        ,FACTURA.RPDCT AS DOC_TIPO
        ,FACTURA.RPKCO AS DOC_COMPANIA
        ,FACTURA.RPSFX AS DOC_LINEA
        
        ,FACTURA.RPVINV AS FACTURA
        ,FACTURA.RPRMK AS DESCRIPCION        
        ,FACTURA.RPPST AS ESTADO
        ,TRIM(ESTADO.DRDL01) AS ESTADO_DESC
        
        ,FACTURA.RPAN8 AS CLIENTE
        ,FACTURA.RPPYR AS BENEFICIARIO
        
        ,CASE WHEN FACTURA.RPDIVJ <> 0 THEN TO_DATE(1900000 + FACTURA.RPDIVJ,'YYYYDDD') END AS FECHA_FACTURA
        ,CASE WHEN FACTURA.RPDDJ <> 0 THEN TO_DATE(1900000 + FACTURA.RPDDJ,'YYYYDDD') END AS FECHA_VENCIMIENTO
        ,CASE WHEN FACTURA.RPJCL <> 0 THEN TO_DATE(1900000 + FACTURA.RPJCL,'YYYYDDD') END AS FECHA_CIERRE
        ,CASE WHEN FACTURA.RPVDGJ <> 0 THEN TO_DATE(1900000 + FACTURA.RPVDGJ,'YYYYDDD') END AS FECHA_ANULACION
        ,CASE WHEN FACTURA.RPDGJ <> 0 THEN TO_DATE(1900000 + FACTURA.RPDGJ,'YYYYDDD') END AS FECHA_LM
        
        ,FACTURA.RPFY AS ANIO
        ,FACTURA.RPCTRY AS CENTURIA
        ,FACTURA.RPPN AS PERIODO
        ,FACTURA.RPCO AS COMPANIA
        
        ,FACTURA.RPICU AS BATCH
        ,FACTURA.RPICUT AS BATCH_TIPO
        ,CASE WHEN FACTURA.RPDICJ <> 0 THEN TO_DATE(1900000 + FACTURA.RPDICJ,'YYYYDDD') END AS BATCH_FECHA
        ,FACTURA.RPPOST AS POSTEO
        
        ,FACTURA.RPAG/100 AS MONTO_TOTAL_MX
        ,FACTURA.RPAAP/100 AS MONTO_PENDIENTE_MX
        ,FACTURA.RPATXA/100 AS MONTO_IMPONIBLE_MX
        ,FACTURA.RPATXN/100 AS MONTO_NOIMPONIBLE_MX
        ,FACTURA.RPSTAM/100 AS MONTO_IMPUESTO_MX
        ,FACTURA.RPTXA1 AS IMPUESTO
        
        ,FACTURA.RPCRCD AS MONEDA
        ,FACTURA.RPCRR AS TASA
        
        ,FACTURA.RPACR/100 AS MONTO_TOTAL_EX
        ,FACTURA.RPFAP/100 AS MONTO_PENDIENTE_EX
        ,FACTURA.RPCTXA/100 AS MONTO_IMPONIBLE_EX
        ,FACTURA.RPCTXN/100 AS MONTO_NOIMPONIBLE_EX
        ,FACTURA.RPCTAM/100 AS MONTO_IMPUESTO_EX
        
        ,FACTURA.RPATAD AS MONTO_XDIST_MX
        ,FACTURA.RPCTAD AS MONTO_XDIST_EX
        
        ,FACTURA.RPGLBA AS BANCO
        ,FACTURA.RPGLC  AS LM
        
        ,TRIM(FACTURA.RPMCU) AS UN
        ,FACTURA.RPSBL AS CUENTA_SUBLIBRO
        ,FACTURA.RPSBLT AS CUENTA_SUB_TIPO
        
        ,FACTURA.RPPTC AS TERMINOS
        ,FACTURA.RPVOD AS FLAG_VOID
        
        ,FACTURA.RPPKCO AS OC_COMPANIA
        ,FACTURA.RPPDCT AS OC_TIPO
        
        ,CASE
          WHEN TRIM(FACTURA.RPPO) IS NULL THEN ' '
          WHEN TRIM(FACTURA.RPPO) IS NOT NULL THEN TO_CHAR(TO_NUMBER(FACTURA.RPPO))
         END AS OC
        
        ,FACTURA.RPSFXO AS OC_SUFIX
        
        ,FACTURA.RPSKCO AS OV_COMPANIA
        ,FACTURA.RPSDCT AS OV_TIPO
        ,FACTURA.RPSDOC AS OV
        ,FACTURA.RPLNID AS OV_LINEA

        
        ,FACTURA.RPITM AS ITEM
        ,FACTURA.RPU AS CANTIDAD
        ,FACTURA.RPUM AS UDM
        
        ,FACTURA.RPTORG AS CREADOR
        ,FACTURA.RPUSER AS UPDATER
        ,CASE WHEN FACTURA.RPUPMJ <> 0 THEN TO_DATE(1900000 + FACTURA.RPUPMJ,'YYYYDDD') END AS FECHA_UPDATE
        
        FROM PRODDTA.F03B11 FACTURA

        LEFT OUTER JOIN PRODCTL.F0005 ESTADO
                     ON ESTADO.DRSY = '00'    
                    AND ESTADO.DRRT = 'PS'    
                    AND TRIM(ESTADO.DRKY) = TRIM(FACTURA.RPPST)
      
        WHERE 1=1
        AND (FACTURA.RPDCT = 'RI' or FACTURA.RPDCT = 'RM') 
        AND FACTURA.RPVDGJ = 0
     )

GROUP BY
  DOC_COMPANIA
  ,DOC_TIPO
  ,DOC
  ,CLIENTE
  ,BENEFICIARIO
  ,UN
  ,FECHA_LM;
