
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "NUVPD"."VIEW_EPAGOS" ("BENEFICIARIO", "PROVEEDOR", "FPAGO", "DOC_COMPANIA", "DOC_TIPO", "DOC", "ANIO", "PERIODO", "MONEDA", "MONTO_PAGO_EX", "MONTO_TOTAL_MX", "CUENTA") AS 
  select 
        CABECERA.RMPYE as BENEFICIARIO --< INDICA EL BENEFICIADO POR EL PAGO (A QUIEN SE DEPOSITO)
        ,LINEA.RNAN8 AS PROVEEDOR      --< INDICA EL PROVEEDOR DE LA FACTURA 
        ,TO_DATE(1900000 + CABECERA.RMDICJ,'YYYYDDD') AS FPAGO
        ,LINEA.RNKCO AS DOC_COMPANIA
        ,LINEA.RNDCT AS DOC_TIPO
        ,LINEA.RNDOC AS DOC
        ,LINEA.RNFY AS ANIO
        ,LINEA.RNPN AS PERIODO
        ,CABECERA.RMCRCD AS MONEDA
       ,SUM((LINEA.RNPFAP/100) * -1) AS MONTO_PAGO_EX
       ,SUM((LINEA.RNPAAP/100) * -1) AS MONTO_TOTAL_MX
        ,CUENTA.GMDL01 AS CUENTA
        from PRODDTA.F0413 CABECERA
        left outer join PRODDTA.F0414 LINEA
                     on LINEA.RNPYID = CABECERA.RMPYID 
        LEFT OUTER JOIN  
               (SELECT GMAID,GMDL01  FROM PRODDTA.F0901) CUENTA
             ON  CABECERA.RMGLBA = CUENTA.GMAID
        WHERE 1=1
        and CABECERA.RMVDGJ = 0     --< QUITAMOS LAS APLICACIONES ANULADAS
        AND LINEA.RNDCTM IN ('PK','PG')    --< Solo registros de PAGOS
        and CABECERA.RMDCTM IN ('PK')  --< Solo registros de PAGOS
        AND LINEA.RNDCT <> 'PX'     --< Quitamos documentos de nomina 
        GROUP BY
        CABECERA.RMPYE
        ,LINEA.RNAN8
        ,LINEA.RNKCO
        ,CABECERA.RMDICJ
        ,LINEA.RNDCT
        ,LINEA.RNDOC
        ,LINEA.RNPN
        ,CABECERA.RMCRCD 
        ,LINEA.RNFY
        ,CUENTA.GMDL01;
