
  CREATE MATERIALIZED VIEW "NUVPD"."VM_CXP" ("PROVEEDOR", "PROVEEDOR_DESC", "BENEFICIARIO_CLASE5", "BENEFICIARIO_CLASE5_DESC", "UN", "UN_DESC", "UN_PROYECTO", "UN_PROYECTO_DESC", "UN_PROYECTO_ZONA", "UN_PROYECTO_TIPO", "UN_PROYECTO_ESTADO", "COMPANIA", "DOC_TIPO", "DOC", "FACTURA", "FECHA_LM", "CUENTA", "CUENTA_NUMERO", "CUENTA_DESC", "CUENTA_CLASE_DESC", "CUENTA_TIPO", "CUENTA_FLUJO", "TOTAL")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 0 INITRANS 2 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT SYSDATE +1
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS SELECT FACTURAS.PROVEEDOR,
       NVL (SUPPLIER.DESCRIPCION, '-') AS BENEFICIARIO_DESC,
       NVL (SUPPLIER.CLASE5, '-') AS BENEFICIARIO_CLASE5,
       NVL (SUPPLIER.CLASE5_DESC, '-') AS BENEFICIARIO_CLASE5_DESC,
       FACTURAS.UN,
       NVL (TRIM (CENTRO.MCDL01), '-') AS UN_DESC,
       NVL (TRIM (CENTRO.MCRP01), '-') AS UN_PROYECTO,
       NVL (TRIM (PROYECTO.DRDL01), '-') AS UN_PROYECTO_DESC,
       NVL (TRIM (PROYECTO.DRDL02), '-') AS UN_PROYECTO_ZONA,
       NVL (TRIM (PROYECTO.DRSPHD), '-') AS UN_PROYECTO_TIPO,
       NVL (TRIM (PROYECTO.DRHRDC), '-') AS UN_PROYECTO_ESTADO,
       FACTURAS.COMPANIA,
       FACTURAS.DOC_TIPO,
       FACTURAS.DOC,
       FACTURAS.FACTURA,
       FACTURAS.FECHA_LM,
       FACTURAS.CUENTA,
       FACTURAS.CUENTA_NUMERO,
       FACTURAS.CUENTA_DESC,
       FACTURAS.CUENTA_CLASE_DESC,
       FACTURAS.CUENTA_TIPO,
       FACTURAS.CUENTA_FLUJO,
       FACTURAS.TOTAL
  FROM NUVPD.VIEW_EP FACTURAS
       LEFT OUTER JOIN PRODDTA.F0006 CENTRO
          ON TRIM (CENTRO.MCMCU) = FACTURAS.UN
       LEFT OUTER JOIN PRODCTL.F0005 PROYECTO
          ON     PROYECTO.DRSY = '00'
             AND PROYECTO.DRRT = '01'
             AND TRIM (PROYECTO.DRKY) = TRIM (CENTRO.MCRP01)
       LEFT OUTER JOIN (SELECT ADDRESS.ABAN8 AS CLAVE,
                               NVL (ADDRESS.ABALPH, '-') AS DESCRIPCION,
                               ADDRESS.ABAT1 AS TIPO,
                               NVL (TRIM (TIPO.DRDL01), '-') AS TIPO_DESC,
                               NVL (TRIM (ADDRESS.ABCLASS05), '-') AS CLASE5,
                               NVL (TRIM (CLASE5.DRDL01), '-') AS CLASE5_DESC
                          FROM PRODDTA.F0101 ADDRESS
                               LEFT OUTER JOIN PRODCTL.F0005 TIPO
                                  ON TIPO.DRSY = '01' AND TIPO.DRRT = 'ST'
                                     AND TRIM (TIPO.DRKY) =
                                            TRIM (ADDRESS.ABAT1)
                               LEFT OUTER JOIN PRODCTL.F0005 CLASE5
                                  ON CLASE5.DRSY = '01'
                                     AND CLASE5.DRRT = 'CE'
                                     AND TRIM (CLASE5.DRKY) =
                                            TRIM (ADDRESS.ABCLASS05)
                         WHERE 1 = 1) SUPPLIER
          ON SUPPLIER.CLAVE = FACTURAS.PROVEEDOR
 WHERE 1 = 1;

   COMMENT ON MATERIALIZED VIEW "NUVPD"."VM_CXP"  IS 'snapshot table for snapshot NUVPD.VM_CXP';
