
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "NUVPD"."VIEW_PM" ("PM_EQUIPO_CLAVE", "PM_EQUIPO_TAG", "PM_SERVICIO", "PM_PROGRAMA_TIPO", "PM_FRECUENCIA", "PM_MULTIPLES_OT", "PM_OT_MODELO", "PM_PROCEDIMIENTO_STD", "PM_CASOS", "PM_FECHA_PROGRAMA", "PM_FECHA_ULT_FINAL", "PM_PORCENTAJE", "PM_ESTADO", "PM_OT_ASIGNADA", "PM_PRIORIDAD", "PM_INACTIVIDAD", "PM_CATEGORIA1", "PM_CATEGORIA2", "PM_OBSERVACIONES", "REGLA_PORCENTAJE_LIM", "REGLA_ESTADO", "REGLA_OT_ORDEN_TIPO", "REGLA_OT_TIPO", "REGLA_OT_PRIORIDAD", "REGLA_ASO_ESTADO_DESDE", "REGLA_ASO_ESTADO_A", "REGLA_METODO_FECHA_INI_PROY", "REGLA_IMPORTE_MUESTRA", "MOD_KIT_CLAVE", "MOD_KIT_NUMERO") AS 
  select
PM.FWNUMB as PM_EQUIPO_CLAVE
,PM.FWAPID as PM_EQUIPO_TAG

,PM.FWSRVT as PM_SERVICIO
,PM.FWPDFG AS PM_PROGRAMA_TIPO

,PM.FWFRIN as PM_FRECUENCIA
,PM.FWMLTW as PM_MULTIPLES_OT
,PM.FWDOCO as PM_OT_MODELO
,PM.FWKY as PM_PROCEDIMIENTO_STD
,PM.FWOCCU/100 as PM_CASOS

,case when PM.FWTDT <> 0 then TO_DATE(1900000 + PM.FWTDT,'yyyyddd') end as PM_FECHA_PROGRAMA
,case when PM.FWLCPD  <> 0 then TO_DATE(1900000 + PM.FWLCPD ,'yyyyddd') end as  PM_FECHA_ULT_FINAL
,PM.FWMPC AS PM_PORCENTAJE

,PM.FWMSTS as PM_ESTADO
,PM.FWWONA as PM_OT_ASIGNADA

,PM.FWMPRI as PM_PRIORIDAD
,PM.FWDNHR as PM_INACTIVIDAD

,PM.FWPMC1 as PM_CATEGORIA1
,PM.FWPMC2 as PM_CATEGORIA2
,PM.FWRMK as PM_OBSERVACIONES

,RUL.GOTHPC as REGLA_PORCENTAJE_LIM
,RUL.GOMSTS as REGLA_ESTADO
,RUL.GODCTO as REGLA_OT_ORDEN_TIPO
,RUL.GOTYPS as REGLA_OT_TIPO
,RUL.GOPRTS as REGLA_OT_PRIORIDAD
,RUL.GOGPFS AS REGLA_ASO_ESTADO_DESDE
,RUL.GOGPTS as REGLA_ASO_ESTADO_A
,RUL.GOPSDM as REGLA_METODO_FECHA_INI_PROY
,RUL.GOSDYS as REGLA_IMPORTE_MUESTRA

,OTM.WAITM as MOD_KIT_CLAVE
,OTM.WAAITM as MOD_KIT_NUMERO

from proddta.F1207 PM

left outer join proddta.F1393 RUL on 1=1
            and RUL.GONUMB = PM.FWNUMB
            and RUL.GOSRVT = PM.FWSRVT
            
left outer join proddta.F4801 OTM on 1=1
            and otm.WADOCO = pm.FWDOCO

where 1=1;
