
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "NUVPD"."VIEW_AUTORIZACIONES" ("ORDEN", "RUTA", "ESTADO", "UN", "OC_COMPANIA", "OC_TIPO", "OC", "OC_SUFIX", "AUTORIZADOR", "AUTORIZADOR_DESC", "AUTORIZACION_FECHA", "AUTORIZACION_HORA", "LISTA_ESTADOS") AS 
  select
ORDEN,
RUTA,
ESTADO,
UN,
OC_COMPANIA,
OC_TIPO,
OC,
OC_SUFIX,
AUTORIZADOR,
AUTORIZADOR_DESC,
AUTORIZACION_FECHA,
AUTORIZACION_HORA,
LISTAGG(to_char(ESTADO),'-') within group (order by ESTADO) over (partition by RUTA, OC_COMPANIA, OC_TIPO, OC) as LISTA_ESTADOS
from (
    select
    ROW_NUMBER() over (partition by HOKCOO,HODCTO,HODOCO,HOSFXO order by HORDJ, HORDT) as ORDEN
    ,HOARTG as RUTA 
    ,TRIM(HOASTS) as ESTADO
    ,HOMCU as UN
    ,HOKCOO as OC_COMPANIA
    ,HODCTO as OC_TIPO
    ,HODOCO as OC
    ,HOSFXO as OC_SUFIX
    ,HORPER as AUTORIZADOR
    ,NVL(TRIM(DIRECCION.ABALPH),'--') as AUTORIZADOR_DESC
    ,case when HORDJ <> 0 then TO_DATE(1900000 + HORDJ,'yyyyddd') else TO_DATE('01/01/1000','DD/MM/YYYY') end as AUTORIZACION_FECHA
    ,HORDT as  AUTORIZACION_HORA
		from PRODDTA.F4209 RUTA 

    /* AUTORIZADORES
    ------------------------------------*/
    left outer join PRODDTA.F0101 DIRECCION on 1=1
                AND DIRECCION.ABAN8 = HORPER
    where 1=1  
    and TRIM(HOASTS) not in ('3N','O')
) 
order by 
    OC_COMPANIA,
    OC_TIPO,
    OC,
    ORDEN;
