
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "NUVPD"."VIEW_RECEPVSCOTEJO" ("OC_COMPANIA", "OC_COMPANIA_DESC", "OC_PROYECTO", "OC_PROYECTO_DESC", "OC_UN", "OC_UN_DESC", "OC_NUMERO", "OC_TIPO", "OC_TIPO_DESC", "OC_LINEA", "OC_LINEA_TIPO", "OC_LINEA_TIPO_DESC", "OC_FECHA_CREACION", "OC_FECHA_CANCELACION", "OC_ESTADO_ULTIMO", "OC_ESTADO_SIGUIENTE", "OC_COMPRADOR", "OC_COMPRADOR_DESC", "OC_ORIGINADOR", "OC_ORIGINADOR_DESC", "OC_PROVEEDOR", "OC_PROVEEDOR_DESC", "OC_ITEM", "OC_ITEM_NUMERO", "OC_ITEM_DESC", "OC_CANTIDAD_SOLIC", "OC_UDM", "OC_UDM_DESC", "OC_CANTIDAD_RECIB", "OC_CANTIDAD_XRECIB", "OC_RECEPCION", "OC_PU_EX", "OC_TOTAL_EX", "OC_MONTO_RECIB_EX", "OC_MONTO_XRECIB_EX", "OC_MONEDA", "OC_TASA", "OC_PU_MX", "OC_TOTAL_MX", "OC_MONTO_RECIB_MX", "OC_MONTO_XRECIB_MX", "RECEPCION_NO", "RECEPCION_COMPANIA", "RECEPCION_TIPO", "RECEPCION_DOC", "RECEPCION_LINEA", "RECEPCION_FECHA", "RECEPCION_FECHA_LM", "RECEPCION_CANTIDAD", "RECEPCION_UDM", "RECEPCION_PU_EX", "RECEPCION_MONTO_EX", "RECEPCION_MONEDA", "RECEPCION_TASA", "RECEPCION_PU_MX", "RECEPCION_MONTO_MX", "RECEPCION_CONTENEDOR", "RECEPCION_BATCH", "RECEPCION_BATCH_TIPO", "RECEPCION_ORIGINADOR", "RECEPCION_ORIGINADOR_DESC", "FAC_COMPANIA", "FAC_TIPO", "FAC", "FAC_LINEA", "FAC_UPDATER", "FAC_UPDATER_DESC", "FAC_FECHA_UPDATE") AS 
  select
        ords.COMPANIA as OC_COMPANIA
        ,ords.COMPANIA_DESC as OC_COMPANIA_DESC
        ,ords.PROYECTO as OC_PROYECTO
        ,ords.PROYECTO_DESC as OC_PROYECTO_DESC
        ,ords.UN as OC_UN
        ,ords.UN_DESC as OC_UN_DESC
        ,ords.NUMERO as OC_NUMERO
        ,ords.TIPO as OC_TIPO
        ,ords.TIPO_DESC as OC_TIPO_DESC
        ,ords.LINEA as OC_LINEA
        ,ords.LINEA_TIPO as OC_LINEA_TIPO
        ,ords.LINEA_TIPO_DESC as OC_LINEA_TIPO_DESC
        ,ords.FECHA_CREACION as OC_FECHA_CREACION
        ,ords.FECHA_CANCELACION as OC_FECHA_CANCELACION
        ,ords.ESTADO_ULTIMO as OC_ESTADO_ULTIMO
        ,ords.ESTADO_SIGUIENTE as OC_ESTADO_SIGUIENTE
        ,ords.COMPRADOR as OC_COMPRADOR
        ,ORDS.COMPRADOR_DESC as OC_COMPRADOR_DESC
        ,ORDS.ORIGINADOR as OC_ORIGINADOR
        ,ords.ORIGINADOR_DESC as OC_ORIGINADOR_DESC
        ,ords.PROVEEDOR as OC_PROVEEDOR
        ,ords.PROVEEDOR_DESC as OC_PROVEEDOR_DESC
        ,ords.ITEM as OC_ITEM
        ,ords.ITEM_NUMERO as OC_ITEM_NUMERO
        ,TRIM(ords.ITEM_DESC1 || ords.ITEM_DESC2 ) as OC_ITEM_DESC
        ,ords.CANTIDAD_SOLIC as OC_CANTIDAD_SOLIC
        ,ords.UDM as OC_UDM
        ,ords.UDM_DESC as OC_UDM_DESC
        ,ords.CANTIDAD_RECIB as OC_CANTIDAD_RECIB
        ,ords.CANTIDAD_XRECIB as OC_CANTIDAD_XRECIB
        ,ords.RECEPCION as OC_RECEPCION
        ,ords.PU_EX as OC_PU_EX
        ,ords.TOTAL_EX as OC_TOTAL_EX
        ,ords.MONTO_RECIB_EX as OC_MONTO_RECIB_EX
        ,ords.MONTO_XRECIB_EX as OC_MONTO_XRECIB_EX
        ,ords.MONEDA as OC_MONEDA
        ,ords.TASA as OC_TASA
        ,ords.PU_MX as OC_PU_MX
        ,ords.TOTAL_MX as OC_TOTAL_MX
        ,ords.MONTO_RECIB_MX as OC_MONTO_RECIB_MX
        ,ORDS.MONTO_XRECIB_MX as OC_MONTO_XRECIB_MX

        ,NVL(RECB.TRAN_LINEA,0) as RECEPCION_NO
        ,NVL(RECB.DOC_COMPANIA,'--') as RECEPCION_COMPANIA
        ,NVL(RECB.DOC_TIPO,'--') as RECEPCION_TIPO       
        ,NVL(RECB.DOC,0) as RECEPCION_DOC
        ,NVL(RECB.DOC_LINEA,0) as RECEPCION_LINEA
        ,NVL(RECB.FECHA_TRAN,TO_DATE('01/01/1000','DD/MM/YYYY')) as RECEPCION_FECHA
        ,nvl(RECB.FECHA_LM,TO_DATE('01/01/1000','DD/MM/YYYY')) as RECEPCION_FECHA_LM
        ,nvl(RECB.CANTIDAD_RECIB,0) as RECEPCION_CANTIDAD
        ,nvl(RECB.UDM_RECIB,'--') as RECEPCION_UDM
        ,nvl(RECB.PU_EX,0) as RECEPCION_PU_EX
        ,nvl(RECB.MONTO_RECIB_EX,0) as RECEPCION_MONTO_EX
        ,nvl(RECB.MONEDA,'--') as RECEPCION_MONEDA
        ,nvl(RECB.TASA,0) as RECEPCION_TASA
        ,nvl(RECB.PU_MX,0) as RECEPCION_PU_MX
        ,NVL(RECB.MONTO_RECIB_MX,0) as RECEPCION_MONTO_MX
        ,NVL(RECB.CONTENEDOR,'--') as RECEPCION_CONTENEDOR
        ,nvl(RECB.BATCH,0) as RECEPCION_BATCH
        ,nvl(RECB.BATCH_TIPO,'--') as RECEPCION_BATCH_TIPO
        ,NVL(RECB.ORIGINADOR,'--') as RECEPCION_ORIGINADOR
        ,nvl(RECB.ORIGINADOR_DESC,'--') AS RECEPCION_ORIGINADOR_DESC
        
        ,NVL(CTE.DOC_COMPANIA, '--') as FAC_COMPANIA
        ,NVL(CTE.DOC_TIPO, '--') as FAC_TIPO
        ,NVL(CTE.DOC, 0) as FAC
        ,NVL(CTE.DOC_LINEA , 0) as FAC_LINEA
        ,NVL(CTE.UPDATER, '--') as FAC_UPDATER
        ,NVL(CTE.UPDATER_DESC,'--') as FAC_UPDATER_DESC
        ,NVL(CTE.FECHA_UPDATE ,TO_DATE('01/01/1000','DD/MM/YYYY')) AS FAC_FECHA_UPDATE 
        
        from NUVPD.VIEW_ORDENES ORDS
        
        left outer join NUVPD.VIEW_RECEPCIONES RECB on 1=1
                    and RECB.OC_COMPANIA = ORDS.COMPANIA
                    and RECB.OC_TIPO = ORDS.TIPO
                    and RECB.OC = ORDS.NUMERO
                    and RECB.OC_SUFIX = ORDS.SUFIX                    
                    and RECB.OC_LINEA = ORDS.LINEA
                    and RECB.TRAN_TIPO = 1
                    
        left outer join NUVPD.VIEW_RECEPCIONES CTE on 1=1
                    and CTE.OC_COMPANIA = RECB.OC_COMPANIA
                    and CTE.OC_TIPO = RECB.OC_TIPO
                    and CTE.OC = RECB.OC
                    and CTE.oc_sufix = RECB.OC_SUFIX
                    and CTE.OC_LINEA = RECB.OC_LINEA
                    AND CTE.TRAN_LINEA = RECB.TRAN_LINEA 
                    and CTE.TRAN_TIPO = 2                   

        where 1=1
        AND ords.TIPO IN ('OS', 'OP', 'OX', 'US', 'UP', 'UX', 'TS', 'SA','OJ')
        
        order by
          ords.COMPANIA
          ,ords.TIPO
          ,ords.NUMERO
          ,ORDS.LINEA
          ,RECB.TRAN_LINEA;
