
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "NUVPD"."VIEW_CARDEX" ("UN", "ITEM", "ITEM_NUMERO", "ITEM_GLCLASS", "DOC_COMANIA", "DOC_TIPO", "DOC", "DESCRIPCION", "FECHA_TRANSACCION", "FECHA_GL", "FECHA_CREACION", "OC_COMPANIA", "OC_TIPO", "OC", "OC_LINEA", "PROVEEDOR", "CANTIDAD", "UDM", "PRECIO_UNITARIO", "PRECIO_TOTAL", "BATCH", "CREATOR") AS 
  select
TRIM(ILMCU)  as UN
,ILITM  as ITEM
,ILLITM as ITEM_NUMERO
,ILGLPT as ITEM_GLCLASS

,ILKCO  as DOC_COMANIA
,ILDCT  as DOC_TIPO
,ILDOC  as DOC
,ILTREX as DESCRIPCION
,case when ILTRDJ <> 0 then TO_DATE(1900000 + ILTRDJ ,'yyyyddd') end as FECHA_TRANSACCION
,case when ILDGL  <> 0 then TO_DATE(1900000 + ILDGL  ,'yyyyddd') end as FECHA_GL
,case when ILCRDJ <> 0 then TO_DATE(1900000 + ILCRDJ ,'yyyyddd') end as FECHA_CREACION

,ILKCOO as OC_COMPANIA
,ILDCTO as OC_TIPO
,ILDOCO as OC
,(ILLNID/1000) as OC_LINEA
,ILAN8  as PROVEEDOR

,ILTRQT/10000 as CANTIDAD
,ILTRUM as UDM
,ILUNCS/10000 as PRECIO_UNITARIO
,ILPAID/100 as PRECIO_TOTAL

,ILICU  as BATCH
,ILUSER as CREATOR

from  PRODDTA.F4111
where 1=1;
