
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "NUVPD"."VIEW_ITEMS" ("CLAVE", "NUMERO", "NOPARTE", "DESCRIPCION", "MODELO", "TEXTO_BUSQUEDA", "ALM_TIPO", "LINEA_TIPO", "GL_CODIGO", "UDM_PRIM", "UDM_SECU", "UDM_COMPRA", "COMPRADOR", "MERCANCIA", "SUBMERCANCIA", "PROVEEDOR_PRIN", "MANTTO_CLASIF", "CODIGO_NORMA_ORDENES", "CD_PLANIF", "REGLA_LIMITE_PLANIF", "LIMITE_CONGELACION", "LIMITE_VISLZ_MENSAJE", "ELIM_MENSAJE_MRP", "NIVEL_PLAZO", "FIJO_FARIABLE") AS 
  SELECT IMITM AS CLAVE,
          IMLITM AS NUMERO,
          TRIM (IMAITM) AS NOPARTE,
          IMDSC1 AS DESCRIPCION,
          IMDSC2 AS MODELO,
          IMSRTX AS TEXTO_BUSQUEDA,
          TRIM (IMSTKT) AS ALM_TIPO,
          TRIM (IMLNTY) AS LINEA_TIPO,
          IMGLPT AS GL_CODIGO,
          IMUOM1 AS UDM_PRIM,
          IMUOM2 AS UDM_SECU,
          IMUOM3 AS UDM_COMPRA,
          IMBUYR AS COMPRADOR,
          IMPRP1 AS MERCANCIA,
          IMPRP2 AS SUBMERCANCIA,
          IMSRP3 AS PROVEEDOR_PRIN,
          IMPRP4 AS MANTTO_CLASIF,
          IMOPC AS CODIGO_NORMA_ORDENES,
          IMMPST AS CD_PLANIF,
          IMMPSP AS REGLA_LIMITE_PLANIF,
          IMMTF2 AS LIMITE_CONGELACION,
          IMMTF3 AS LIMITE_VISLZ_MENSAJE,
          IMLMFG AS ELIM_MENSAJE_MRP,
          IMLTLV AS NIVEL_PLAZO,
          IMMRPP AS FIJO_FARIABLE
     FROM PRODDTA.F4101 ITEM
    WHERE 1 = 1;
