
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "NUVPD"."VIEW_UNIDADES" ("CLAVE", "TIPO", "COMPANIA", "DESC_CORTA", "DESC_LARGA", "RECLASS") AS 
  select 
TRIM(MCMCU) as CLAVE,
NVL(TRIM(MCSTYL),'--') as TIPO,
MCCO as COMPANIA,
MCDL01 as DESC_CORTA,
TRIM(MCMCU) || ' : ' || TRIM(MCDL01||MCDL02) as DESC_LARGA, 
NVL(TRIM(MCRP50),'--') as RECLASS
from PRODDTA.F0006 where 1=1
--and MCSTYL in ('F1','F2', 'DP', 'DR' , 'ST', 'PA', 'GE') 
--AND MCRP50 <> 'HST'

--and mcpecc <> 'N' 
--order by 1
;
