
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "NUVPD"."VIEW_ITEM_ALMACEN" ("COMPANIA", "UN", "ITEM_CLAVE", "ITEM_NUMERO", "ITEM_NOPARTE", "ITEM_DESCRIPCION", "ITEM_MODELO", "ITEM_TEXTO_BUSQUEDA", "ALM_TIPO", "LINEA_TIPO", "GL_CODIGO", "UDM_PRIM", "UDM_SECU", "UDM_COMPRA", "PROVEEDOR", "PLANEADOR", "COMPRADOR", "MERCANCIA", "SUBMERCANCIA", "PROVEEDOR_PRIN", "MANTTO_CLASIF", "CODIGO_NORMA_ORDENES", "CD_PLANIF", "REGLA_LIMITE_PLANIF", "LIMITE_CONGELACION", "LIMITE_VISLZ_MENSAJE", "ELIM_MENSAJE_MRP", "CODIGO_TP_ENVIO", "NIVEL_PLAZO", "FIJO_FARIABLE", "MAXIMO", "MINIMO", "CANTIDAD_ORDEN_MULTIPLE", "CANTIDAD_PUNTO_ORDEN", "PUNTO_ORDEN", "STOCK_SEGURIDAD") AS 
  select
  CENTRO.MCCO AS COMPANIA
  ,TRIM(ITEAM.IBMCU) as UN
  ,ITEAM.IBITM as ITEM_CLAVE
  ,TRIM(ITEAM.IBLITM) as ITEM_NUMERO
  ,TRIM(ITEAM.IBAITM) as ITEM_NOPARTE
  
  ,ITEM.IMDSC1 as ITEM_DESCRIPCION
  ,ITEM.IMDSC2 as ITEM_MODELO
  ,ITEM.IMSRTX as ITEM_TEXTO_BUSQUEDA  
  
  ,TRIM(ITEAM.IBSTKT) as ALM_TIPO
  ,TRIM(ITEAM.IBLNTY) as LINEA_TIPO
  ,ITEAM.IBGLPT as GL_CODIGO
  ,ITEM.IMUOM1 as UDM_PRIM
  ,ITEM.IMUOM2 as UDM_SECU
  ,ITEM.IMUOM3 as UDM_COMPRA  
  ,ITEAM.IBVEND as PROVEEDOR
  ,ITEAM.IBANPL as PLANEADOR
  ,ITEAM.IBBUYR as COMPRADOR
  ,ITEAM.IBPRP1 as MERCANCIA
  ,ITEAM.IBPRP2 as SUBMERCANCIA
  ,ITEAM.IBSRP3 as PROVEEDOR_PRIN
  ,ITEAM.IBPRP4 as MANTTO_CLASIF
  
  ,ITEAM.IBOPC as  CODIGO_NORMA_ORDENES
  ,ITEAM.IBMPST as CD_PLANIF
  ,ITEAM.IBMPSP as REGLA_LIMITE_PLANIF
  ,ITEAM.IBMTF2 as LIMITE_CONGELACION
  ,ITEAM.IBMTF3 as LIMITE_VISLZ_MENSAJE
  ,ITEAM.IBLMFG as ELIM_MENSAJE_MRP
  ,ITEAM.IBITC as CODIGO_TP_ENVIO
  ,ITEAM.IBLTLV as NIVEL_PLAZO
  ,ITEAM.IBMRPP as FIJO_FARIABLE

  ,ITEAM.IBRQMX/10000 as MAXIMO
  ,ITEAM.IBRQMN/10000 as MINIMO
  ,ITEAM.IBMULT/10000 as CANTIDAD_ORDEN_MULTIPLE

  ,ITEAM.IBROQI/10000 as CANTIDAD_PUNTO_ORDEN
  ,ITEAM.IBROPI/10000 as PUNTO_ORDEN
  ,ITEAM.IBSAFE/10000 as STOCK_SEGURIDAD

from PRODDTA.F4102 ITEAM 
left outer join PRODDTA.F4101 ITEM on 1=1 
            AND ITEM.IMITM = ITEAM.IBITM
            
left outer join PRODDTA.F0006 CENTRO on 1=1
            and CENTRO.MCMCU = ITEAM.IBMCU;
